### ISSUE TITLE
Example for styling header rows incorrect

### ISSUE THREAD

**Issue by halcyonandon** [wyuenho/backgrid#161]
Should be 

``` css
.backgrid th {
  background-image: linear-gradient(#ffffff, #eeeeee);
}
```
