### ISSUE TITLE
Server-side sorting failing on prototype chain check.

### ISSUE THREAD

**Issue by jacek-kantox** [wyuenho/backgrid#653]
Hi!

I am not a JS expert, however I have a collection which inherits from `Backbone.PageableCollection`, using CofeeScript `extends`:

```
class SomeApp.Collections.Items extends Backbone.PageableCollection
  model: SomeApp.Models.BaseModel

  url: ->
    App.config.url_root_data

  mode: 'server'

  state:
    pageSize: 2
    sortKey: 'created_time_stamp'
    order: 1

  queryParams:
    totalPages: null
    totalRecords: null
    sortKey: 'sort'

  parseState: (resp, queryParams, state, options) ->
    { totalRecords: resp.total_entries }

  parseRecords: (resp, options) ->
    resp.entries
```

The problem is that I cannot use server-side column sorting as [this](https://github.com/wyuenho/backgrid/blob/master/lib/backgrid.js#L2577) `instanceof` check returns `false`.

When checked in the console the `__proto__` attribute of `collection` points to `Backbone.PageableCollection.Backbone.Collection.extend.constructor` while it's `constructor` is `function Items`.

However, doing this:  `collection.__proto__ = Backbone.PageableCollection.prototype` in the console returns `true` for the check while both `__proto__` and the prototype constructor point to `Backbone.Collection`.

I am wondering where this behaviour comes from (actually I can see that the check returns `true` for `Items`, `Backbone.Collection` and `Object`, but not for `Backbone.PageableCollection`) and how can I get around this to get the server-side sorting working...
